config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/", to: "welcome#index"

  get "/venues", to: "venues#index"
  get "/venues/new", to: "venues#new"
  get "/venues/:id", to: "venues#show"
  post "/venues", to: "venues#create"
  get "/venues/:id/edit", to: "venues#edit"
  patch "/venues/:id", to: "venues#update"
  delete "/venues/:id", to: "venues#delete"

  get "/shows", to: "shows#index"
  get "/shows/:id", to: "shows#show"
  get "/shows/:id/edit", to: "shows#edit"
  patch "/shows/:id", to: "shows#update"
  delete "/shows/:id", to: "shows#delete"

  get "/venues/:id/shows", to: "venue_shows#index"
  get "/venues/:id/shows/new", to: "venue_shows#new"
  post "/venues/:id/shows", to: "venue_shows#create"
  get "/venues/:id/shows/sort", to: "venue_shows#sort"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :venue
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :shows

  def show_count
    self.shows.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end

  def show
    @show = Show.find(params[:id])
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    show = Show.find(params[:id])
    show.update({
      artist_name: params[:artist_name],
      price: params[:price],
      sold_out: params[:sold_out] == "true"
    })

    show.save
    redirect_to "/shows/#{show.id}"
  end

  def delete
    show.destroy(params[:id])

    redirect_to "/shows"
  end
end

app/controllers/venue_shows_controller.rb
class VenueShowsController < ApplicationController
  def index
    @venue = Venue.find(params[:id])
    @venue_shows = @venue.shows
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.order(created_at: :desc)
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def new
  end

  def create
    venue = Venue.create!({
      name: params[:name],
      city: params[:city],
      capacity: params[:capacity],
      open: params[:open] == "true"
    })

    redirect_to "/venues"
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    venue = Venue.find(params[:id])
    venue.update({
      name: params[:name],
      city: params[:city],
      capacity: params[:capacity],
      open: params[:open] == "true"
    })

    venue.save
    redirect_to "/venues/#{venue.id}"
  end

  def delete
    Venue.destroy(params[:id])

    redirect_to "/venues"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VenueManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/index.html.erb
<nav>
<%= link_to "Venues Index", venues_path %>
</nav>

<h1>Shows</h1>  

<% @shows.each do |show| %>
  <h3>Artist: <%= show.artist_name %></h3>
  <p>Price: <%= show.price %></p>
  <p>Sold Out? <%= show.sold_out %></p>
<% end %>

app/views/shows/show.html.erb
<nav>
<%= link_to "Shows Index", shows_path %>
<%= link_to "Venues Index", venues_path %>
</nav>

<h1><%= @show.artist_name %></h1>

<p><b>Price: </b><%= @show.price%></p>

<p><b>This show is sold out: </b><%= @show.sold_out%></p>

<%= link_to "Update Show<", "/shows/#{@show.id}/edit" %>

<%= button_to "Delete", "/shows/#{@show.id}", method: :delete %>

app/views/venue_shows/index.html.erb
<nav>
<%= link_to "Shows Index", shows_path %>
<%= link_to "Venues Index", venues_path %>
</nav>

<h1> Shows at: <%= @venue.name %></h1>

<%= link_to "Add Show", "/venues/#{@venue.id}/shows/new" %></br>

<%= link_to "Sort Shows", :sort_by => "artist_name" %>

<% @venue_shows.each do |show| %>
  <h3><%= show.artist_name %></h3>
  <p><b>Price: </b><%= show.price %></p>
  <p><b>This show is sold out: </b><%= show.sold_out %></p>

  <%= button_to "Delete #{show.artist_name}", "/shows/#{show.id}", method: :delete %>
<% end %>

app/views/venues/edit.html.erb
<nav>
  <%= link_to "Shows", "/shows" %></br>
  <%= link_to "Venues", "/venues" %>
</nav>

<form action="/venues/<%= @venue.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH" />
  <p><b>Edit Venue</b></p>
  <input type='text' id='name' name='name' value='name'/><br/>
  <input type='text' id='city' name='city' value='city'/><br/>
  <input type='number' id='capacity' name='capacity' min='1'/>
  <label for='capacity'> capacity</label><br/>
  <input type='radio' id='open' name='open' value='true'>
  <label for='open'> venue is open</label><br/>
  <input type='radio' id='closed' name='closed' value='false'>
  <label for='closed'> venue is closed</label><br/>
  <button type='submit' name='submit' value='submit'>Submit</>

</form>

app/views/venues/index.html.erb
<nav>
<%= link_to "Shows Index", shows_path %>
</nav>

<h1>Venues</h1>  

<%= link_to "New Venue", "/venues/new" %></br></br>


<% @venues.each do |venue| %> 
  <%= link_to "#{venue.name}", "/venues/#{venue.id}" %> Created At: <%= venue.created_at %></br>
      
  <%= button_to "Delete #{venue.name}", "/venues/#{venue.id}", method: :delete %>
<% end %>  

app/views/venues/new.html.erb
<center>
  <h1>New Venue</h1>
<section class="new-card card">
  <div class=" card-body">
    <%= form_with url: '/venues', method: :post, data: { turbo: false } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "enter venue name" %> 
      <%= f.label :city %>
      <%= f.text_field :city, placeholder: "enter city" %>
      <%= f.label :capacity %>
      <%= f.text_field :capacity, placeholder: "enter capacity" %>
      <%= f.label :open %> 
      <%= f.text_field :open, placeholder: "enter true or false" %>
      <%= f.submit 'Create Venue', class: 'button' %>
    <% end %>
  </div>
</center>

app/views/venues/show.html.erb
<%= link_to "Shows Index", shows_path %>
<%= link_to "Venues Index", venues_path %>

<h1><%= @venue.name %></h1>
<p>Location: <%= @venue.city %></p>
<p>Capacity: <%= @venue.capacity %></p>
<p>Open? <%= @venue.open %></p>
<p># of Shows: <%= @venue.show_count %></p>
<%= link_to "This Venues Shows", "/venues/#{@venue.id}/shows" %></br></br>

<%= link_to "Update #{@venue.name}", "/venues/#{@venue.id}/edit" %></br>

<%= button_to "Delete", "/venues/#{@venue.id}", method: :delete %>